plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jorge.dexcorrect'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jorge.dexcorrect'
        minSdk 21
        targetSdk 35

        versionCode 3
        versionName '0.3'
    }

    signingConfigs {
        debug {
            storeFile file('../signing/dexcorrect-test.jks')
            storePassword 'dexcorrect123'
            keyAlias 'dexcorrect'
            keyPassword 'dexcorrect123'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
